### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by lzytniak** [barbalion/usbip-win-client#1]
Please provide any documentation how to run client.
I think installation was almost successful:
![image](https://user-images.githubusercontent.com/8569463/69172798-cc132880-0afe-11ea-9468-b933709b788c.png)

I can't list any devices:
![image](https://user-images.githubusercontent.com/8569463/69173877-f960d600-0b00-11ea-9de5-b642f855687a.png)

USBIP server is working because I can see connected devices on other USBIP client on Linux:
![image](https://user-images.githubusercontent.com/8569463/69174157-8c9a0b80-0b01-11ea-8f12-b506a73270ea.png)

**Comment by barbalion** [comment]
Sorry for disappointing you, but the repository is discontinued at the moment :(
Since there is no good driver for Windows 10, I don't maintain, nor test it.

**Comment by barbalion** [comment]
A bit of documentation in readme. I can't imagine any more at the moment.
