### ISSUE TITLE
How to remove all configs

### ISSUE THREAD

**Issue by erikthegamer1242** [barbalion/usbip-win-client#3]
How can I remove all configs 
![image](https://user-images.githubusercontent.com/71411196/93395411-29d6e500-f876-11ea-9678-96d50374f8b7.png)
How can I make it soo it doesn't pick up old config (removed services, drivers, signatures, and deleted the folder and unzipped it again)
Thanks in advance.

**Comment by barbalion** [comment]
You can simply remove `usbip.conf` file. I'll consider making it configurable.
