### ISSUE TITLE
After I install

### ISSUE THREAD

**Issue by bmcunha** [barbalion/usbip-win-client#4]
I already installed but I'm having this issue installing the service.
![error01](https://user-images.githubusercontent.com/34158123/93589196-60ab1900-f9a4-11ea-8e12-183c2062117f.jpg)
I already deleted the service with `sc delete "USB-Over-IP Service"` and I run the install again and I got the same output.
What I'm doing wrong?

**Comment by barbalion** [comment]
Try running `uninstall.cmd`, reboot the system and run `install.cmd` again.

**Comment by barbalion** [comment]
Also check Windows Defender activity. It may block the scripts/executables. Run all the executable one by one (without parameters - it will not harm your system) to 'introduce' Defender with the new files, and allow all confirmations if any.
